### ISSUE TITLE
mkdirp function does not work first time

### ISSUE THREAD

**Issue by jdeck88** [mariadeck/cpad-tester#3]
first time we run mkdirp it only creates output/State
2nd time we run mkdirp it creates output/State/University+of+California

appears that it is not working recursively.  Search web for fix and implement

**Comment by mariadeck** [comment]
mkdirp was not running because all the functions were running asynchronously. I've put the file writing function as a callback to the mkdirp function, to make sure the directory is created before the files are written.... this works, but the console.log on line 91 isn't working

**Comment by jdeck88** [comment]
This works now.
