### ISSUE TITLE
Run additional datasets

### ISSUE THREAD

**Issue by jdeck88** [mariadeck/cpad-tester#4]
Run the job to harvest data for the following entities (we need to make sure the job runs on these and for example, not encounter encoding issues or other problems along the way).  

output / State / California Department of Parks and Recreation
output / State / California Department of Forestry and Fire Protection
output / State / California Department of Fish and Wildlife
output / Special District / East Bay Regional Park District
output / Federal / United States National Park Service
output / Federal / United States Forest Service
output / Federal / United States Bureau of Land Management
output / Federal / United States Army Corps of Engineers

**Comment by mariadeck** [comment]
State California+Department+of+Parks+and+Recreation
State California+Department+of+Forestry+and+Fire+Protection
State California+Department+of+Fish+and+Wildlife
Special+District East+Bay+Regional+Park+District
Federal United+States+National+Park+Service
Federal United+States+Forest+Service
Federal United+States+Bureau+of+Land+Management
Federal United+States+Army+Corps+of+Engineers
